### ISSUE TITLE
Condition parsing and evaluation question

### ISSUE THREAD

**Issue by cdondrup** [iocchi/PetriNetPlans#9]
Hi,

I am slowly working my way through the code but have a few questions regarding the condition evaluation at runtime and the condition parsing during PNP generation I couldn't answer so far.

1.  I had a look at pnpgen and from this statement: [`boost::algorithm::split_regex( strs, line, boost::regex( "\\*[^ ]*\\*" ) ) ;`](https://github.com/iocchi/PetriNetPlans/blob/master/PNPgen/src/pnpgenerator.cpp#L614) I suspect that the actual keyword between the two `*` is irelevant. In fact I tried changing

  ```
*if* condition *during* action *do* recovery
  ```

  to 

  ```
*foo* condition *bar* action *foobar* recovery
  ```

  and it still worked all the same. The keyword `during`, however had me hoping that there would be a `before` and `after` as well but I couldn't find something like that. I guess that would be easiest to implement by adding a sensing/evaluation action before or after the action in question. The problem is that currently the action starts executing and would then be interrupted once the condition is false, however, if you have let's say a `say` action that uses a tts which listens on a topic and then synthesises the speech, this is not interruptible once the string has been sent. Hence, if there in fact is no such thing in pnpgen, it might be interesting for others as well so I would attempt to implement it.
  
1. I noticed that there are special procedures in pnpgen to add an interrupt of an action but not to deal with it failing. At least I couldn't find one. I found the functionality that allows to handle this for [`action.fail`](https://github.com/iocchi/PetriNetPlans/blob/master/PNP/src/basic_plan/xml_plan_instantiator.cpp#L143-L167) but couldn't find how to use this in pnpgen. The are keywords for failing the plan or restarting it but I couldn't find how to add an execution rule in case the action fails. I'm not sure if this might be possible with the [conditional plan](https://github.com/iocchi/PetriNetPlans/blob/master/PNPgen/src/pnpgenerator.cpp#L799-L820) functionality because I couldn't find an example for that but from the source that seems to be more focused on sensing actions. If nothing like this exists, I would implement it.

1. Lastly, I would like to know how the conditions are parsed. I noticed that special symbols like ` ` (space) or `:` lead to a parsing error. I had a look at the parser but that has too many `goto`s for me to properly understand what it actually does. Are there special symbols with a reserved meaning? And if so, what are they used for? From the readme I get that `@` is used for variables but are there any others? I also noticed that for plan generation, if the action has a `-` in the name some part of it is interpreted as a condition apparently. So, if there is a list of special symbols and do's and don'ts for the parsing, I would very much appreciate a pointer.

Thanks for the help and sorry for the wall of text.

**Comment by iocchi** [comment]
1. At this moment, only the *during* rule is implemented and so the 
behavior of the statement
is exactly as you described. *before* and *after* are no my TODO list... 
some implementation
of before/after is already present in the code but not linked with the 
parser of the execution rules file.
I can try to do something in this direction in the next days, if you 
need it.
However, I do not understand your example about tts, which behaviour 
would you like to obtain from PNPgen
and PNP?

2. I think the concept of a PNP action failing is not clear. In PNP an 
action is either running or not running.
Whether a non-running action succeeded or not is not really represented 
in PNP.
The concept of plain failure is instead implemented with a place 
labelled with 'FAIL'
As for adding an execution rule in case an action fail, the idea is that 
when an action fails
(i.e., some component of the robot determines that the action has 
failed), this is due to some condition
(to which you have to give a name, e.g. "action_failed", if you don't 
find a better one).
Then this condition can be used to end/interrupt the action with an 
execution rule like
*if* action_failed *during* ....

3. Special characters used in names of actions and conditions are:
_ for separating parameters  (e.g., goto_kitchen, will invoke action 
goto with parameter kitchen)
@ for variables (e.g., goto_@Location, will invoke action goto with the 
value of variable Location)
# for specifying multiple agents in Multi-Robot PNP (e.g., 
robot1#goto_kitchen, will invoke the action for robot1)
Many other special characters are not allowed (i.e., generate parsing 
errors).

Best regards,
Luca.


Il 04/08/2016 17:50, Christian Dondrup ha scritto:

**Comment by cdondrup** [comment]
Hi Luca,

Thanks for the quick reply.

1. Regarding the tts, let's assume I have a tts system running that takes a string and synthesises text. From an external component I can send it a string and then the tts does the rest. For this external component, the action of sending this string is instantaneous. Hence, once the action is started the string is sent and the robot will inevitably start speaking so if the condition is only tested while the action is running, it is already too late to prevent the robot from saying anything even though the condition might have been false all the time. Therefore, I would like to be able to specify that this condition has to be true before attempting the action. Having seen the execution rules I thought that it would be easiest (from a users point of view) to just define something like `*if* (not human_there) *before* say *do* fail_plan`. I can also just use an additional sensing action before the say to do just that but since I am just getting to grips with the whole PNP architecture, that was a bit less intuitive for me. But this is not urgent. I will work around it with sensing actions.

1. I think that I am very much biased by the ROS way of thinking. If an action is carried out by an action server, then this server responds either success, preempted/recall, or aborted/lost. These final states of the server are communicated when the action returns. This can then of course be added into the KB and queried via the condition evaluation but since PNP already offers special behaviour for a failing action: https://github.com/iocchi/PetriNetPlans/blob/master/PNP/src/basic_plan/xml_plan_instantiator.cpp#L159-L165 I thought that it would be more natural to use it like that. I will try the KB way for now but think that in general using `action.fail` is a concept that could be used in those cases.

1. Thank you! That is very good to know.

**Comment by iocchi** [comment]
1. Yes, in this case a sensing action before the speech action is needed since if some condition indicates that the robot should not speak, then the action should not be started at all. A *before* rule could also work, but I think in this case a sensing action is more appropriate, since you want to check if a precondition for the actions holds before executing it.

2. I agree we can work on this feature as well.

**Comment by cdondrup** [comment]
Regarding 2. I already added the necessary function to [my version of the ActionProxy](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server/PNPros/ROS_bridge/pnp_ros/src/ActionProxy.cpp#L259-L276) in PNPros. Now it is just a case of having the option of creating the neccessary places and transitions automatically using pnpgen. I assume that just using a slightly different version of the [addInterrupt()](https://github.com/iocchi/PetriNetPlans/blob/master/PNPgen/src/pnpgenerator.cpp#L334-L343) might do it. Something like this, maybe:

```cpp
Transition* PNP::addFail(Place *pi Place *po) {
    Node *pe = next(next(pi)); // exec place
    string ae=pe->getName();
    std::size_t pos = ae.find(".");      // position of "." in str
    std::string a = ae.substr(0,pos);
    Transition *ts = addTransition(a+".fail");
    ts->setY(pe->getY()-1); ts->setX(pe->getX()); // upper line wrt pe
    connect(pe,ts); connect(ts,po);
    return ts;
}
```

Then we would only need a special keyword like `restart_plan` for the condition to trigger the failure behaviour, e.g. `*if* action_failed *during* my_say_action *do* restart_action`. And then something like this:

```cpp
void PNPGenerator::applyExecutionRules() {

    pair<string, Place*> current; Place* noplace=NULL;
    while (!ASE.empty()) {
        current=ASE.top(); ASE.pop();
        
        ...
        if(eit->condition=="action_failed")
                Transition *tsi = pnp.addFail(current_place,pi);
        else
                Transition *tsi = pnp.addInterrupt(current_place,eit->condition,pi);
                

         ...
         eit++;

    }
}
```

This is of course only my naive attempt at accomplishing this so I am not sure if there are any other problems with this behaviour.

I am very sorry for taking all your time btw. but I really appreciate all your help. Just FYI. we would like to use PNPs in the [MuMMER project](http://mummer-project.eu/) for all the necessary task management. We'll be using it with ROS indigo on Ubuntu 14.04, hence, why I keep coming back to the ROS modules ;) And as I said in #8, I already got it work on our pepper robot.

**Comment by iocchi** [comment]
No problem. I am very glad to solve problems and improve this part.
I am also very happy if you will use this software in the MuMMER project.
We have successfully tested the same code (but based on MDP) in the [COACHES](https://coaches.greyc.fr/) project which is very similar to MuMMER.

**Comment by cdondrup** [comment]
That is partially why we want use it and because of @marc-hanheide saying great things about it ;)

Have a look at #12 please and let me know what you think.

**Comment by cdondrup** [comment]
I have another quick question: if I have `fail_plan` as a recovery, is it somehow communicated that the plan failed? I would like to trigger replanning in a ros component but for that I would need to know that the plan failed in the first place. What would be the easiest way to find that out?

**Comment by iocchi** [comment]
Yes. PNPros publishes on the topic pnp/currentActivePlaces a string the labels of all the current active places. When you reach a fail place, you will receive the label fail on this topic.

**Comment by cdondrup** [comment]
Brilliant. Thank you!

**Comment by cdondrup** [comment]
Hi, I have just seen all the changes regarding the failure management and that this is correctly published in ROS now. Works brilliantly. Thank you very much!
